export class Follow {
    constructor(
        public id: string,
        public seguimiento_pot: boolean,
        public pa: string,
        public fc: boolean,
        public fr: boolean,
        public temperatura: string,
        public pulsioximetria: boolean,
        public tos: boolean,
        public dolor_garganta: boolean,
        public congestion_nasal: boolean,
        public fiebre: boolean,
        public malestar_general: boolean,
        public dificultad_respiratoria: boolean,
        public diarrea: boolean,
        public nausea_vomito: boolean,
        public cefalea: boolean,
        public irritabilidad_confusion: boolean,
        public dolor_muscular: boolean,
        public dolor_abdominal: boolean,
        public dolor_pecho: boolean,
        public dolor_articulaciones: boolean,
        public otro_signo_sintoma: string,
        public disnea: boolean,
        public taquipnea: boolean,
        public saturacion_oxigeno: boolean,
        public alteracion_conciencia: boolean,
        public fosfato_cloroquina: boolean,
        public hidorxicloroquina: boolean,
        public azitromicina: boolean,
        public otro_tratamiento_especifico: string,
        public antibiotico: string,
        public antiviral: string,
        public onoxapirina: string,
        public otro_anticoagulatorio: string,
        public especificar_medicamento: string,
        public estado_evolucion: string,
        public condicion_egreso: string,
        public patient: string,
    ){}
}